---
# Install Docker Engine on Debian - https://docs.docker.com/engine/install/debian/
- hosts: vagrant_debian10
  become: yes
  vars:  
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  # Install Docker
  - name: Install Docker prerequisites
    apt:
      name:
        - ca-certificates 
        - curl 
        - gnupg
        - lsb-release

  - name: Add Docker's official GPG key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Install Docker
    shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  
  - name: Remove Docker's official GPG key
    file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      state: absent

  - name: Remove get-docker.sh
    file:
      path: get-docker.sh
      state: absent

  - name: Add User Permissions to Docker group
    shell: sudo usermod -aG docker vagrant

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true

  # Install Docker SDK
  - name: Install Python3 pip
    apt:
      name: 
        - python3-pip
  
  - name: Install Python SDK
    pip:
      name: docker
      executable: pip3

  # https://www.jeffgeerling.com/blog/2021/allowing-ansible-playbooks-work-new-user-groups-on-first-run
  # - name: Reload a Linux user's group assignments without logging out
  #   shell: sg docker -c "docker --version"

  # - name: Test Docker user access
  #   shell: docker --version