---
# Install Docker Engine on Debian - https://docs.docker.com/engine/install/debian/
- hosts: vagrant_debian10
  become: yes
  tasks:

  - name: Install Docker prerequisites
    apt:
      name:
        - ca-certificates 
        - curl 
        - gnupg
        - lsb-release

  - name: Add Docker's official GPG key
    ansible.builtin.shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

  - name: Install Docker
    ansible.builtin.shell: curl -fsSL https://get.docker.com -o get-docker.sh && sudo sh get-docker.sh
  
  - name: Remove Docker's official GPG key
    ansible.builtin.file:
      path: /usr/share/keyrings/docker-archive-keyring.gpg
      state: absent

  - name: Remove get-docker.sh
    ansible.builtin.file:
      path: get-docker.sh
      state: absent

  - name: Add User Permissions to Docker group
    ansible.builtin.shell: sudo usermod -aG docker vagrant

  - name: Ensure docker deamon is running
    service:
      name: docker
      state: started
    become: true

  # https://www.jeffgeerling.com/blog/2021/allowing-ansible-playbooks-work-new-user-groups-on-first-run
  # - name: Reload a Linux user's group assignments without logging out
  #   ansible.builtin.command: sg docker -c "docker --version"

  # - name: Test Docker user access
  #   ansible.builtin.shell: docker --version