---
# Start an initial timeoff-app container
- hosts: vagrant_debian10
  become: yes
  vars:  
    ansible_python_interpreter: /usr/bin/python3
  tasks:

  - name: Copy timeoff-app docker-compose with owner and permissions
    copy:
      src: timeoff-app/files/docker-compose.yaml
      dest: /home/vagrant/docker-compose.yaml
      owner: vagrant
      group: vagrant
      mode: '0644'

  - name: Start a timeoff-app container using docker-compose
    docker_service:
      project_src: /home/vagrant/
      files: docker-compose.yaml
